### ISSUE TITLE
Make a 512-bit hasher base

### ISSUE THREAD

**Issue by mborland** [cppalliance/crypt#34]
MD5, SHA1, SHA256, SHA224 all use nearly the same code outside of the hashing function. Put this common functionality in an abstract base class to reduce code repetition (and possible repeated errors)

**Comment by mborland** [comment]
What do you think @ckormanyos ? `process_message_block` and `get_digest` so that we only need to implement those two functions for every hasher. CUDA is fine with virtual functions as long as they don't pass the host to device interface since the V-table will be on the wrong platform.

**Comment by ckormanyos** [comment]
> What do you think @ckormanyos ? `process_message_block` and `get_digest` so that we only need to implement those two functions for every hasher.

Yes. That is exactly what I've done in other designs. I think you need to copy backward/forward for the digest on MD/SHA families, but that's just a detail on the extraction of the digest result.

The process function on a block does, I beleive, possibly have varying process-block sizes, so this might need to be a template parameter. To be honest it's been a while since I did all that. So we can see how it is for all the hashes.

**Comment by mborland** [comment]
Cool. I wanted to make sure that having virtual functions isn't going to cause any issues on your metal platforms.

**Comment by ckormanyos** [comment]
> Cool. I wanted to make sure that having virtual functions isn't going to cause any issues on your metal platforms.

Yes Matt (@mborland) that is a valid point and I'm happy you addressed this one. I feel, however, that the virtual function mechanism is trivially small compared to the effort to hash a block. So we are safe there and all metal platforms deal with this very efficiently these days.

In some of my previous designs I have definitely used the base-class/derived-class approach many times. But it can also be effective to mix this with template length parameters in so far as these might be needed, that is if the current design benefits from this.

P.S. I also saw the CAVS updates in another issue and will comply to these in my future testing.
